import { Inter, Radio_Canada } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const radioCanada = Radio_Canada({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="customTheme" lang="en">
      <body className={inter.className + " max-w-[1440px] mx-auto"}>
        {children}
      </body>
      {/* <body className={radioCanada.className}>{children}</body> */}
    </html>
  );
}
