export const countryList = [
  { value: "", caption: "Select Country" },
  { value: "26", caption: "Afghanistan" },
  { value: "27", caption: "Albania" },
  { value: "28", caption: "Algeria" },
  { value: "29", caption: "Andorra" },
  { value: "30", caption: "Angola" },
  { value: "31", caption: "Antigua and Barbuda" },
  { value: "32", caption: "Argentina" },
  { value: "33", caption: "Armenia" },
  { value: "34", caption: "Australia" },
  { value: "35", caption: "Austria" },
  { value: "36", caption: "Azerbaijan" },
  { value: "37", caption: "Bahamas" },
  { value: "38", caption: "Bahrain" },
  { value: "39", caption: "Bangladesh" },
  { value: "40", caption: "Barbados" },
  { value: "41", caption: "Belarus" },
  { value: "42", caption: "Belgium" },
  { value: "43", caption: "Belize" },
  { value: "44", caption: "Benin" },
  { value: "45", caption: "Bermuda" },
  { value: "46", caption: "Bhutan" },
  { value: "47", caption: "Bolivia" },
  { value: "48", caption: "Bosnia and Herzegovina" },
  { value: "49", caption: "Botswana" },
  { value: "50", caption: "Brazil" },
  { value: "51", caption: "British Virgin Islands" },
  { value: "52", caption: "Brunei" },
  { value: "53", caption: "Bulgaria" },
  { value: "54", caption: "Burkina Faso" },
  { value: "55", caption: "Cambodia" },
  { value: "56", caption: "Cameroon" },
  { value: "57", caption: "Canada" },
  { value: "58", caption: "Cayman Islands" },
  { value: "59", caption: "Central African Republic" },
  { value: "60", caption: "Chad" },
  { value: "61", caption: "Chile" },
  { value: "62", caption: "China" },
  { value: "63", caption: "Colombia" },
  { value: "64", caption: "Comoros" },
  { value: "65", caption: "Congo" },
  { value: "66", caption: "Costa Rica" },
  { value: "67", caption: "Cote dIvoire" },
  { value: "68", caption: "Croatia" },
  { value: "69", caption: "Cuba" },
  { value: "70", caption: "Cyprus" },
  { value: "71", caption: "Czech Republic" },
  { value: "72", caption: "Denmark" },
  { value: "73", caption: "Djibouti" },
  { value: "74", caption: "Dominica" },
  { value: "75", caption: "Dominican Republic" },
  { value: "76", caption: "Ecuador" },
  { value: "77", caption: "Egypt" },
  { value: "78", caption: "El Salvador" },
  { value: "79", caption: "Equatorial Guinea" },
  { value: "80", caption: "Eritrea" },
  { value: "81", caption: "Estonia" },
  { value: "82", caption: "Ethiopia" },
  { value: "83", caption: "Fiji" },
  { value: "84", caption: "Finland" },
  { value: "85", caption: "France" },
  { value: "86", caption: "Gabon" },
  { value: "87", caption: "Gambia" },
  { value: "88", caption: "Georgia" },
  { value: "89", caption: "Germany" },
  { value: "90", caption: "Ghana" },
  { value: "91", caption: "Greece" },
  { value: "92", caption: "Grenada" },
  { value: "93", caption: "Guatemala" },
  { value: "94", caption: "Guinea" },
  { value: "95", caption: "Guinea-Bissau" },
  { value: "96", caption: "Guyana" },
  { value: "97", caption: "Haiti" },
  { value: "98", caption: "Honduras" },
  { value: "224", caption: "Hong Kong" },
  { value: "99", caption: "Hungary" },
  { value: "100", caption: "Iceland" },
  { value: "101", caption: "India" },
  { value: "102", caption: "Indonesia" },
  { value: "103", caption: "Iran" },
  { value: "104", caption: "Iraq" },
  { value: "105", caption: "Ireland" },
  { value: "106", caption: "Israel" },
  { value: "107", caption: "Italy" },
  { value: "108", caption: "Jamaica" },
  { value: "109", caption: "Japan" },
  { value: "110", caption: "Jordan" },
  { value: "111", caption: "Kazakhstan" },
  { value: "112", caption: "Kenya" },
  { value: "113", caption: "Kiribati" },
  { value: "114", caption: "Kosovo" },
  { value: "115", caption: "Kuwait" },
  { value: "116", caption: "Kyrgyzstan" },
  { value: "117", caption: "Laos" },
  { value: "118", caption: "Latvia" },
  { value: "119", caption: "Lebanon" },
  { value: "120", caption: "Lesotho" },
  { value: "121", caption: "Liberia" },
  { value: "122", caption: "Libya" },
  { value: "123", caption: "Liechtenstein" },
  { value: "124", caption: "Lithuania" },
  { value: "125", caption: "Luxembourg" },
  { value: "126", caption: "Macedonia" },
  { value: "127", caption: "Madagascar" },
  { value: "128", caption: "Malawi" },
  { value: "129", caption: "Malaysia" },
  { value: "130", caption: "Maldives" },
  { value: "131", caption: "Mali" },
  { value: "132", caption: "Malta" },
  { value: "133", caption: "Marshall Islands" },
  { value: "134", caption: "Mauritania" },
  { value: "135", caption: "Mauritius" },
  { value: "136", caption: "Mexico" },
  { value: "137", caption: "Micronesia" },
  { value: "138", caption: "Moldova" },
  { value: "139", caption: "Monaco" },
  { value: "140", caption: "Mongolia" },
  { value: "141", caption: "Montenegro" },
  { value: "142", caption: "Morocco" },
  { value: "143", caption: "Mozambique" },
  { value: "144", caption: "Myanmar (Burma)" },
  { value: "145", caption: "Namibia" },
  { value: "146", caption: "Nauru" },
  { value: "147", caption: "Nepal" },
  { value: "148", caption: "Netherlands" },
  { value: "149", caption: "New Zealand" },
  { value: "150", caption: "Nicaragua" },
  { value: "151", caption: "Niger" },
  { value: "152", caption: "Nigeria" },
  { value: "153", caption: "North Korea" },
  { value: "154", caption: "Norway" },
  { value: "155", caption: "Oman" },
  { value: "156", caption: "Pakistan" },
  { value: "157", caption: "Palau" },
  { value: "158", caption: "Palestine" },
  { value: "159", caption: "Panama" },
  { value: "160", caption: "Papua New Guinea" },
  { value: "161", caption: "Paraguay" },
  { value: "162", caption: "Peru" },
  { value: "163", caption: "Philippines" },
  { value: "164", caption: "Poland" },
  { value: "165", caption: "Portugal" },
  { value: "166", caption: "Qatar" },
  { value: "167", caption: "Romania" },
  { value: "168", caption: "Russia" },
  { value: "169", caption: "Rwanda" },
  { value: "170", caption: "Saint Kitts and Nevis" },
  { value: "171", caption: "Saint Lucia" },
  { value: "172", caption: "Saint Vincent and the Grenadines" },
  { value: "173", caption: "Samoa" },
  { value: "174", caption: "San Marino" },
  { value: "175", caption: "Sao Tome and Principe" },
  { value: "176", caption: "Saudi Arabia" },
  { value: "177", caption: "Senegal" },
  { value: "178", caption: "Serbia" },
  { value: "179", caption: "Seychelles" },
  { value: "180", caption: "Sierra Leone" },
  { value: "181", caption: "Singapore" },
  { value: "182", caption: "Slovakia" },
  { value: "183", caption: "Slovenia" },
  { value: "184", caption: "Solomon Islands" },
  { value: "185", caption: "Somalia" },
  { value: "186", caption: "South Africa" },
  { value: "187", caption: "South Korea" },
  { value: "188", caption: "South Sudan" },
  { value: "189", caption: "Spain" },
  { value: "190", caption: "Sri Lanka" },
  { value: "191", caption: "Sudan" },
  { value: "192", caption: "Suriname" },
  { value: "193", caption: "Swaziland" },
  { value: "194", caption: "Sweden" },
  { value: "195", caption: "Switzerland" },
  { value: "196", caption: "Syria" },
  { value: "197", caption: "Taiwan" },
  { value: "198", caption: "Tajikistan" },
  { value: "199", caption: "Tanzania" },
  { value: "200", caption: "Thailand" },
  { value: "201", caption: "Timor-Leste" },
  { value: "202", caption: "Togo" },
  { value: "203", caption: "Tonga" },
  { value: "204", caption: "Trinidad and Tobago" },
  { value: "205", caption: "Tunisia" },
  { value: "206", caption: "Turkey" },
  { value: "207", caption: "Turkmenistan" },
  { value: "208", caption: "Tuvalu" },
  { value: "209", caption: "Uganda" },
  { value: "210", caption: "Ukraine" },
  { value: "211", caption: "United Arab Emirates" },
  { value: "212", caption: "United Kingdom" },
  { value: "213", caption: "United States of America" },
  { value: "214", caption: "Uruguay" },
  { value: "215", caption: "Uzbekistan" },
  { value: "216", caption: "Vanuatu" },
  { value: "217", caption: "Vatican City" },
  { value: "218", caption: "Venezuela" },
  { value: "219", caption: "Vietnam" },
  { value: "220", caption: "Yemen" },
  { value: "222", caption: "Zambia" },
  { value: "221", caption: "Zimbabwe" },
];
