export const reports = [
  {
    id: 2,
    title: "Green Cement Market",
    slug: "green-cement-market-2",
    summary:
      "Rising environmental concerns and government regulations on carbon emissionsIncreasing demand for sustainable construction materialsTechnological advancements in gr",
    price: {
      multiPrice: "5850",
      singlePrice: "4850",
      enterprisePrice: "6850",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2023",
    noOfPages: "250",
  },
  {
    id: 3,
    title: "Example Title 2",
    slug: "example-title-2",
    summary: "Example Summary 2",
    price: {
      multiPrice: "6000",
      singlePrice: "5000",
      enterprisePrice: "7000",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2022",
    noOfPages: "300",
  },
  {
    id: 4,
    title: "Example Title 3",
    slug: "example-title-3",
    summary: "Example Summary 3",
    price: {
      multiPrice: "6200",
      singlePrice: "5200",
      enterprisePrice: "7200",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2021",
    noOfPages: "350",
  },

  {
    id: 5,
    title: "Example Title 4",
    slug: "example-title-4",
    summary: "Example Summary 4",
    price: {
      multiPrice: "6300",
      singlePrice: "5300",
      enterprisePrice: "7300",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2020",
    noOfPages: "400",
  },
  {
    id: 6,
    title: "Example Title 5",
    slug: "example-title-5",
    summary: "Example Summary 5",
    price: {
      multiPrice: "6400",
      singlePrice: "5400",
      enterprisePrice: "7400",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2019",
    noOfPages: "450",
  },
  {
    id: 7,
    title: "Example Title 6",
    slug: "example-title-6",
    summary: "Example Summary 6",
    price: {
      multiPrice: "6500",
      singlePrice: "5500",
      enterprisePrice: "7500",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2018",
    noOfPages: "500",
  },
  {
    id: 8,
    title: "Example Title 7",
    slug: "example-title-7",
    summary: "Example Summary 7",
    price: {
      multiPrice: "6600",
      singlePrice: "5600",
      enterprisePrice: "7600",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2017",
    noOfPages: "550",
  },
  {
    id: 9,
    title: "Example Title 8",
    slug: "example-title-8",
    summary: "Example Summary 8",
    price: {
      multiPrice: "6700",
      singlePrice: "5700",
      enterprisePrice: "7700",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2016",
    noOfPages: "600",
  },
  {
    id: 10,
    title: "Example Title 9",
    slug: "example-title-9",
    summary: "Example Summary 9",
    price: {
      multiPrice: "6800",
      singlePrice: "5800",
      enterprisePrice: "7800",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2015",
    noOfPages: "650",
  },
  {
    id: 11,
    title: "Example Title 10",
    slug: "example-title-10",
    summary: "Example Summary 10",
    price: {
      multiPrice: "6900",
      singlePrice: "5900",
      enterprisePrice: "7900",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2014",
    noOfPages: "700",
  },
  {
    id: 12,
    title: "Example Title 11",
    slug: "example-title-11",
    summary: "Example Summary 11",
    price: {
      multiPrice: "7000",
      singlePrice: "6000",
      enterprisePrice: "8000",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2013",
    noOfPages: "750",
  },
  {
    id: 13,
    title: "Example Title 12",
    slug: "example-title-12",
    summary: "Example Summary 12",
    price: {
      multiPrice: "7100",
      singlePrice: "6100",
      enterprisePrice: "8100",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2012",
    noOfPages: "800",
  },
  {
    id: 14,
    title: "Example Title 13",
    slug: "example-title-13",
    summary: "Example Summary 13",
    price: {
      multiPrice: "7200",
      singlePrice: "6200",
      enterprisePrice: "8200",
    },
    createdAt: "2024-03-24T06:53:55.663Z",
    baseyear: "2011",
    noOfPages: "850",
  },
];

export const categories = [
  {
    id: 1,
    label: "Healthcare",
    link: "healthcare-industry",
    icon: "Hospital",
    parentCategory: null,
    parent: null,
    createdAt: "2024-03-24T06:53:29.171Z",
  },
  {
    id: 2,
    label: "Medical Device",
    link: "medical-device-industry",
    parentCategory: 1,
    parent: {
      label: "Healthcare",
      link: "healthcare-industry",
    },
    createdAt: "2024-03-24T06:53:29.213Z",
  },
];

export const parentCategory = [
  {
    id: 1,
    label: "Healthcare",
    link: "healthcare-industry",
    icon: "Hospital",
    parentCategory: null,
    parent: null,
    createdAt: "2024-03-24T06:53:29.171Z",
  },
  {
    id: 2,
    label: "Healthcare-2",
    link: "healthcare-industry",
    icon: "Hospital",
    parentCategory: null,
    parent: null,
    createdAt: "2024-03-24T06:53:29.171Z",
  },
  {
    id: 3,
    label: "Healthcare-3",
    link: "healthcare-industry",
    icon: "Hospital",
    parentCategory: null,
    parent: null,
    createdAt: "2024-03-24T06:53:29.171Z",
  },
  {
    id: 4,
    label: "Healthcare-4",
    link: "healthcare-industry",
    icon: "Hospital",
    parentCategory: null,
    parent: null,
    createdAt: "2024-03-24T06:53:29.171Z",
  },
];

const report = {
  basic: {
    id: 2,
    title: "Green Cement Market ",
    marketKeyword: "Green Cement Market ",
    marketData: {
      cagr: "9.9",
      valueUnit: "USD Billion",
      marketSize: "",
      volumeUnit: "Kiloton",
      isValueAvailable: true,
      isVolumeAvailable: true,
    },
    price: {
      multiPrice: "5850",
      singlePrice: "4850",
      enterprisePrice: "6850",
    },
    region: "Global ",
    baseyear: "2023",
    createdAt: "2024-03-24T06:53:55.663Z",
    category: {
      label: "Building & Construction Materials",
      link: "building-and-construction-materials-industry",
    },
  },
  marketAnalysis: {
    id: 2,
    reportId: 2,
    companies: [
      "JSW Cement (India)",
      "Green Cement Inc. (U.S.)",
      "Holcim Ltd. (Switzerland)",
      "ACC Limited (India)",
      "UltraTech Cement Limited (India)",
      "Anhui Conch Cement (China)",
      "CEMEX S.A.B. de C.V. (Mexico)",
      "CRH plc (Ireland)",
      "CarbonCure Technologies Inc. (Nova Scotia)",
      "Heidelberg Cement (Germany)",
    ],
    segments: [
      "Type: Fly Ash, Slag, Recycled Aggregate, and Others",
      "Application: Residential, Non-Residential, and Infrastructure",
    ],
    developments: [
      "November 2023:  Heidelberg Cement launched the low-carbon cement brand to reduce greenhouse gas emissions during the cement manufacturing and mixing process.",
      "October 2022: JSW Cement planned to invest USD 390 million to begin an integrated green cement production facility in Madhya Pradesh and a split grinding unit in Uttar Pradesh. The proposed investment includes a 2.5 MTPA grinding capacity, 15 MW Waste heat recovery system, and 2.5 MTPA clinker capacity.",
      "July 2022: Hallett Group launched a USD 125 million valued green cement project to reduce CO2 emissions by 300,000 tons annually, located across Port Adelaide, Port Augusta, Port Pirie, and Whyalla.",
      "July 2021: Holcim launched ECOPlanet, a range of green cement delivering at least 30 lower carbon footprints with equal to superior performance. It is available in Romania, Germany, Switzerland, Canada, France, Spain, and Italy and will be distributed across 15 countries in 2021.",
      "January 2023: ACC Limited introduced ‘ACC ECOMaxX’, a range of green concrete solutions. The products are developed using a Unique Green Ready Mix Technology, which allows for maximizing green impact by reducing CO2 emissions by up to 100%.",
      "March 2023: Holcim Mexico commenced manufacturing its Fuerte Más reduced-CO2 cement at its cement plants in Tabasco and Macuspana at a combined rate of 60,000t/yr.",
    ],
    regionData: [
      "North America :U.S. ,Canada ",
      "Europe :Germany ,U.K. ,France ,Italy ,Rest of Europe ",
      "Asia Pacific :China ,Japan ,India ,South Korea ,Rest of Asia Pacific ",
      "Rest of World :Latin America ,Middle East & Africa ",
    ],
    createdAt: "2024-03-24T06:53:55.663Z",
    updatedAt: "2024-03-24T06:53:55.663Z",
  },
  marketReport: {
    id: 2,
    reportId: 2,
    drivers: "Increasing Demand from Residential Sector to Fuel Market Growth ",
    trends:
      "Growing Adoption of Green Cement over Traditional Cement to Stimulate Market Growth",
    restrains:
      "Manufacturers Switching from Conventional to Greener Cement to Restrain Market Growth  ",
    createdAt: "2024-03-24T06:53:55.663Z",
    updatedAt: "2024-03-24T06:53:55.663Z",
  },
  rd: {
    id: 2,
    reportId: 2,
    rd: "<p><strong>Green Cement Market Report</strong></p>\n<p><strong>Executive Summary</strong></p>\n<p>The green cement market is poised for rapid growth in the coming years, driven by increasing environmental awareness and stringent regulations aimed at reducing carbon emissions from the construction industry. This report provides a comprehensive analysis of the global green cement market, examining market size, growth drivers, challenges, and key trends.</p>\n<p><strong>Market Size and Forecast</strong></p>\n<p>The global green cement market was valued at USD 20.5 billion in 2022 and is projected to reach USD 45.7 billion by 2030, exhibiting a CAGR of 10.2% during the forecast period. The Asia Pacific region holds the largest market share due to the growing construction activities and government initiatives promoting sustainability.</p>\n<p><strong>Growth Drivers</strong></p>\n<ul>\n<li>Rising environmental concerns and government regulations on carbon emissions</li>\n<li>Increasing demand for sustainable construction materials</li>\n<li>Technological advancements in green cement production</li>\n<li>Growing awareness of the health benefits of low-carbon cement</li>\n</ul>\n<p><strong>Challenges</strong></p>\n<ul>\n<li>Higher production costs compared to traditional cement</li>\n<li>Limited availability of raw materials</li>\n<li>Lack of standardization in green cement specifications</li>\n<li>Competition from traditional cement manufacturers</li>\n</ul>\n<p><strong>Key Trends</strong></p>\n<ul>\n<li>Adoption of innovative technologies, such as fly ash, slag, and biomass-based cements</li>\n<li>Development of new cement formulations with reduced carbon footprint</li>\n<li>Partnerships between construction companies and green cement suppliers</li>\n<li>Government incentives and funding for green cement projects</li>\n</ul>\n<p><strong>Competitive Landscape</strong></p>\n<p>The green cement market is highly fragmented, with several major players and emerging startups. Key players include:</p>\n<ul>\n<li>LafargeHolcim</li>\n<li>HeidelbergCement</li>\n<li>Cemex</li>\n<li>UltraTech Cement</li>\n<li>Boral</li>\n</ul>\n<p><strong>Conclusion</strong></p>\n<p>The green cement market is expected to witness significant growth in the coming years as the construction industry embraces sustainability initiatives. Technological advancements, government regulations, and consumer demand for eco-friendly products will continue to drive market expansion. By investing in green cement, manufacturers and construction companies can reduce their environmental impact and meet the sustainability demands of the future.</p>",
    chart: null,
    createdAt: "2024-03-24T07:01:09.733Z",
    updatedAt: "2024-03-24T07:01:09.733Z",
  },
};
